# This file was generated by liblab | https://liblab.com/

from typing import Union
from typing import List
from .utils.json_map import JsonMap
from .utils.base_model import BaseModel
from .utils.one_of_base_model import OneOfBaseModel


class ValueGuard(OneOfBaseModel):
    class_list = {
        "str": str,
        "float": float,
        "int": int,
        "List[any]": List[any],
        "dict": dict,
    }


Value = Union[str, float, int, List[any], dict]


@JsonMap({})
class AdditionalParameter(BaseModel):
    """AdditionalParameter

    :param name: name
    :type name: str
    :param value: value
    :type value: List[Value]
    """

    def __init__(self, name: str, value: List[Value]):
        """AdditionalParameter

        :param name: name
        :type name: str
        :param value: value
        :type value: List[Value]
        """
        self.name = name
        self.value = self._define_list(value, Value)
