# This file was generated by liblab | https://liblab.com/

from __future__ import annotations
from typing import Union
from .utils.one_of_base_model import OneOfBaseModel
from .point_geo_json import PointGeoJson
from .multipoint_geo_json import MultipointGeoJson
from .linestring_geo_json import LinestringGeoJson
from .multilinestring_geo_json import MultilinestringGeoJson
from .polygon_geo_json import PolygonGeoJson
from .multipolygon_geo_json import MultipolygonGeoJson
from .geometrycollection_geo_json import GeometrycollectionGeoJson


class GeometryGeoJsonGuard(OneOfBaseModel):
    class_list = {
        "PointGeoJson": PointGeoJson,
        "MultipointGeoJson": MultipointGeoJson,
        "LinestringGeoJson": LinestringGeoJson,
        "MultilinestringGeoJson": MultilinestringGeoJson,
        "PolygonGeoJson": PolygonGeoJson,
        "MultipolygonGeoJson": MultipolygonGeoJson,
        "GeometrycollectionGeoJson": GeometrycollectionGeoJson,
    }


GeometryGeoJson = Union[
    PointGeoJson,
    MultipointGeoJson,
    LinestringGeoJson,
    MultilinestringGeoJson,
    PolygonGeoJson,
    MultipolygonGeoJson,
    GeometrycollectionGeoJson,
]
