# This file was generated by liblab | https://liblab.com/

from enum import Enum


class GetOgrAddressesGpkgFeaturesProperties(Enum):
    """An enumeration representing different categories.

    :cvar ID: "id"
    :vartype ID: str
    :cvar STRAATNAAM: "straatnaam"
    :vartype STRAATNAAM: str
    :cvar HUISNUMMER: "huisnummer"
    :vartype HUISNUMMER: str
    :cvar HUISLETTER: "huisletter"
    :vartype HUISLETTER: str
    :cvar WOONPLAATS: "woonplaats"
    :vartype WOONPLAATS: str
    :cvar POSTCODE: "postcode"
    :vartype POSTCODE: str
    :cvar TOEVOEGING: "toevoeging"
    :vartype TOEVOEGING: str
    """

    ID = "id"
    STRAATNAAM = "straatnaam"
    HUISNUMMER = "huisnummer"
    HUISLETTER = "huisletter"
    WOONPLAATS = "woonplaats"
    POSTCODE = "postcode"
    TOEVOEGING = "toevoeging"

    def list():
        """Lists all category values.

        :return: A list of all category values.
        :rtype: list
        """
        return list(
            map(
                lambda x: x.value,
                GetOgrAddressesGpkgFeaturesProperties._member_map_.values(),
            )
        )
