# This file was generated by liblab | https://liblab.com/

from enum import Enum


class GetUnescoPoisItalyFeaturesProperties(Enum):
    """An enumeration representing different categories.

    :cvar GMLID: "gml_id"
    :vartype GMLID: str
    :cvar CODUNESCO: "cod_unesco"
    :vartype CODUNESCO: str
    :cvar SITO: "sito"
    :vartype SITO: str
    :cvar SERIALE: "seriale"
    :vartype SERIALE: str
    :cvar CODCOMPON: "cod_compon"
    :vartype CODCOMPON: str
    :cvar COMPONENTE: "componente"
    :vartype COMPONENTE: str
    :cvar TIPOAREA: "tipo_area"
    :vartype TIPOAREA: str
    """

    GMLID = "gml_id"
    CODUNESCO = "cod_unesco"
    SITO = "sito"
    SERIALE = "seriale"
    CODCOMPON = "cod_compon"
    COMPONENTE = "componente"
    TIPOAREA = "tipo_area"

    def list():
        """Lists all category values.

        :return: A list of all category values.
        :rtype: list
        """
        return list(
            map(
                lambda x: x.value,
                GetUnescoPoisItalyFeaturesProperties._member_map_.values(),
            )
        )
