# This file was generated by liblab | https://liblab.com/

from enum import Enum


class GetLandingPageF(Enum):
    """An enumeration representing different categories.

    :cvar JSON: "json"
    :vartype JSON: str
    :cvar HTML: "html"
    :vartype HTML: str
    :cvar JSONLD: "jsonld"
    :vartype JSONLD: str
    """

    JSON = "json"
    HTML = "html"
    JSONLD = "jsonld"

    def list():
        """Lists all category values.

        :return: A list of all category values.
        :rtype: list
        """
        return list(map(lambda x: x.value, GetLandingPageF._member_map_.values()))
