# This file was generated by liblab | https://liblab.com/

from enum import Enum


class GetUtahCityLocationsFeaturesProperties(Enum):
    """An enumeration representing different categories.

    :cvar GMLID: "gml_id"
    :vartype GMLID: str
    :cvar NAME: "NAME"
    :vartype NAME: str
    :cvar COSEAT: "CO_SEAT"
    :vartype COSEAT: str
    :cvar POP1999: "POP_1999"
    :vartype POP1999: str
    :cvar POPSYM99: "POP_SYM_99"
    :vartype POPSYM99: str
    :cvar POP2000: "POP_2000"
    :vartype POP2000: str
    :cvar POPSYM00: "POP_SYM_00"
    :vartype POPSYM00: str
    :cvar STATE: "STATE"
    :vartype STATE: str
    """

    GMLID = "gml_id"
    NAME = "NAME"
    COSEAT = "CO_SEAT"
    POP1999 = "POP_1999"
    POPSYM99 = "POP_SYM_99"
    POP2000 = "POP_2000"
    POPSYM00 = "POP_SYM_00"
    STATE = "STATE"

    def list():
        """Lists all category values.

        :return: A list of all category values.
        :rtype: list
        """
        return list(
            map(
                lambda x: x.value,
                GetUtahCityLocationsFeaturesProperties._member_map_.values(),
            )
        )
