# This file was generated by liblab | https://liblab.com/

from enum import Enum


class GetDutchGeorefStationsFeaturesProperties(Enum):
    """An enumeration representing different categories.

    :cvar GMLID: "gml_id"
    :vartype GMLID: str
    :cvar GID: "gid"
    :vartype GID: str
    :cvar BLAD: "blad"
    :vartype BLAD: str
    :cvar PUNT: "punt"
    :vartype PUNT: str
    :cvar STATION: "station"
    :vartype STATION: str
    :cvar JAAR: "jaar"
    :vartype JAAR: str
    :cvar MAAND: "maand"
    :vartype MAAND: str
    :cvar DAG: "dag"
    :vartype DAG: str
    :cvar OMSCHREXT: "omschrext"
    :vartype OMSCHREXT: str
    :cvar OMSCHRINT: "omschrint"
    :vartype OMSCHRINT: str
    :cvar XRD: "xrd"
    :vartype XRD: str
    :cvar YRD: "yrd"
    :vartype YRD: str
    :cvar PHI: "phi"
    :vartype PHI: str
    :cvar LAMBDA: "lambda"
    :vartype LAMBDA: str
    :cvar H: "h"
    :vartype H: str
    :cvar GPS: "gps"
    :vartype GPS: str
    :cvar PEILMERK: "peilmerk"
    :vartype PEILMERK: str
    :cvar FUUID: "fuuid"
    :vartype FUUID: str
    """

    GMLID = "gml_id"
    GID = "gid"
    BLAD = "blad"
    PUNT = "punt"
    STATION = "station"
    JAAR = "jaar"
    MAAND = "maand"
    DAG = "dag"
    OMSCHREXT = "omschrext"
    OMSCHRINT = "omschrint"
    XRD = "xrd"
    YRD = "yrd"
    PHI = "phi"
    LAMBDA = "lambda"
    H = "h"
    GPS = "gps"
    PEILMERK = "peilmerk"
    FUUID = "fuuid"

    def list():
        """Lists all category values.

        :return: A list of all category values.
        :rtype: list
        """
        return list(
            map(
                lambda x: x.value,
                GetDutchGeorefStationsFeaturesProperties._member_map_.values(),
            )
        )
