# This file was generated by liblab | https://liblab.com/

from enum import Enum


class GetDutchCastlesFeaturesProperties(Enum):
    """An enumeration representing different categories.

    :cvar GMLID: "gml_id"
    :vartype GMLID: str
    :cvar GID: "gid"
    :vartype GID: str
    :cvar CCHIN: "cchin"
    :vartype CCHIN: str
    :cvar NAAM: "naam"
    :vartype NAAM: str
    :cvar PLAATS: "plaats"
    :vartype PLAATS: str
    :cvar INFOLINK: "info_link"
    :vartype INFOLINK: str
    :cvar DATERING: "datering"
    :vartype DATERING: str
    :cvar RIJKSMONNR: "rijksmonnr"
    :vartype RIJKSMONNR: str
    :cvar PROVINCIE: "provincie"
    :vartype PROVINCIE: str
    :cvar FOTOTHUMB: "foto_thumb"
    :vartype FOTOTHUMB: str
    :cvar FOTOGROOT: "foto_groot"
    :vartype FOTOGROOT: str
    :cvar BIJSCHRIFT: "bijschrift"
    :vartype BIJSCHRIFT: str
    :cvar ZICHTBAAR: "zichtbaar"
    :vartype ZICHTBAAR: str
    :cvar LEGENDA: "legenda"
    :vartype LEGENDA: str
    :cvar TYPERING: "typering"
    :vartype TYPERING: str
    """

    GMLID = "gml_id"
    GID = "gid"
    CCHIN = "cchin"
    NAAM = "naam"
    PLAATS = "plaats"
    INFOLINK = "info_link"
    DATERING = "datering"
    RIJKSMONNR = "rijksmonnr"
    PROVINCIE = "provincie"
    FOTOTHUMB = "foto_thumb"
    FOTOGROOT = "foto_groot"
    BIJSCHRIFT = "bijschrift"
    ZICHTBAAR = "zichtbaar"
    LEGENDA = "legenda"
    TYPERING = "typering"

    def list():
        """Lists all category values.

        :return: A list of all category values.
        :rtype: list
        """
        return list(
            map(
                lambda x: x.value,
                GetDutchCastlesFeaturesProperties._member_map_.values(),
            )
        )
