# This file was generated by liblab | https://liblab.com/

from enum import Enum


class GetLakesFeaturesProperties(Enum):
    """An enumeration representing different categories.

    :cvar ID: "id"
    :vartype ID: str
    :cvar SCALERANK: "scalerank"
    :vartype SCALERANK: str
    :cvar NAME: "name"
    :vartype NAME: str
    :cvar NAMEALT: "name_alt"
    :vartype NAMEALT: str
    :cvar ADMIN: "admin"
    :vartype ADMIN: str
    :cvar FEATURECLASS: "featureclass"
    :vartype FEATURECLASS: str
    """

    ID = "id"
    SCALERANK = "scalerank"
    NAME = "name"
    NAMEALT = "name_alt"
    ADMIN = "admin"
    FEATURECLASS = "featureclass"

    def list():
        """Lists all category values.

        :return: A list of all category values.
        :rtype: list
        """
        return list(
            map(lambda x: x.value, GetLakesFeaturesProperties._member_map_.values())
        )
