# This file was generated by liblab | https://liblab.com/

from enum import Enum


class GetDutchMetadataFeaturesProperties(Enum):
    """An enumeration representing different categories.

    :cvar CREATED: "created"
    :vartype CREATED: str
    :cvar UPDATED: "updated"
    :vartype UPDATED: str
    :cvar TYPE: "type"
    :vartype TYPE: str
    :cvar TITLE: "title"
    :vartype TITLE: str
    :cvar DESCRIPTION: "description"
    :vartype DESCRIPTION: str
    :cvar PROVIDERS: "providers"
    :vartype PROVIDERS: str
    :cvar EXTERNALIDS: "externalIds"
    :vartype EXTERNALIDS: str
    :cvar THEMES: "themes"
    :vartype THEMES: str
    :cvar EXTENT: "extent"
    :vartype EXTENT: str
    :cvar Q: "q"
    :vartype Q: str
    """

    CREATED = "created"
    UPDATED = "updated"
    TYPE = "type"
    TITLE = "title"
    DESCRIPTION = "description"
    PROVIDERS = "providers"
    EXTERNALIDS = "externalIds"
    THEMES = "themes"
    EXTENT = "extent"
    Q = "q"

    def list():
        """Lists all category values.

        :return: A list of all category values.
        :rtype: list
        """
        return list(
            map(
                lambda x: x.value,
                GetDutchMetadataFeaturesProperties._member_map_.values(),
            )
        )
