# This file was generated by liblab | https://liblab.com/

from enum import Enum


class GetDutchWindmillsFeaturesProperties(Enum):
    """An enumeration representing different categories.

    :cvar GMLID: "gml_id"
    :vartype GMLID: str
    :cvar GID: "gid"
    :vartype GID: str
    :cvar NAAM: "NAAM"
    :vartype NAAM: str
    :cvar PLAATS: "PLAATS"
    :vartype PLAATS: str
    :cvar CATEGORIE: "CATEGORIE"
    :vartype CATEGORIE: str
    :cvar FUNCTIE: "FUNCTIE"
    :vartype FUNCTIE: str
    :cvar TYPE: "TYPE"
    :vartype TYPE: str
    :cvar STAAT: "STAAT"
    :vartype STAAT: str
    :cvar RMONNUMMER: "RMONNUMMER"
    :vartype RMONNUMMER: str
    :cvar TBGCNUMMER: "TBGCNUMMER"
    :vartype TBGCNUMMER: str
    :cvar INFOLINK: "INFOLINK"
    :vartype INFOLINK: str
    :cvar THUMBNAIL: "THUMBNAIL"
    :vartype THUMBNAIL: str
    :cvar HFDFUNCTIE: "HFDFUNCTIE"
    :vartype HFDFUNCTIE: str
    :cvar FOTOGRAAF: "FOTOGRAAF"
    :vartype FOTOGRAAF: str
    :cvar FOTOGROOT: "FOTO_GROOT"
    :vartype FOTOGROOT: str
    :cvar BOUWJAAR: "BOUWJAAR"
    :vartype BOUWJAAR: str
    """

    GMLID = "gml_id"
    GID = "gid"
    NAAM = "NAAM"
    PLAATS = "PLAATS"
    CATEGORIE = "CATEGORIE"
    FUNCTIE = "FUNCTIE"
    TYPE = "TYPE"
    STAAT = "STAAT"
    RMONNUMMER = "RMONNUMMER"
    TBGCNUMMER = "TBGCNUMMER"
    INFOLINK = "INFOLINK"
    THUMBNAIL = "THUMBNAIL"
    HFDFUNCTIE = "HFDFUNCTIE"
    FOTOGRAAF = "FOTOGRAAF"
    FOTOGROOT = "FOTO_GROOT"
    BOUWJAAR = "BOUWJAAR"

    def list():
        """Lists all category values.

        :return: A list of all category values.
        :rtype: list
        """
        return list(
            map(
                lambda x: x.value,
                GetDutchWindmillsFeaturesProperties._member_map_.values(),
            )
        )
