# This file was generated by liblab | https://liblab.com/

from enum import Enum


class GetOgrGpkgWalesRailwayLinesFeaturesProperties(Enum):
    """An enumeration representing different categories.

    :cvar ID: "id"
    :vartype ID: str
    :cvar TYPE: "type"
    :vartype TYPE: str
    """

    ID = "id"
    TYPE = "type"

    def list():
        """Lists all category values.

        :return: A list of all category values.
        :rtype: list
        """
        return list(
            map(
                lambda x: x.value,
                GetOgrGpkgWalesRailwayLinesFeaturesProperties._member_map_.values(),
            )
        )
