# This file was generated by liblab | https://liblab.com/

from enum import Enum


class GetOgrGpkgPoiFeaturesProperties(Enum):
    """An enumeration representing different categories.

    :cvar GID: "gid"
    :vartype GID: str
    :cvar OSMID: "osm_id"
    :vartype OSMID: str
    :cvar FCLASS: "fclass"
    :vartype FCLASS: str
    :cvar NAME: "name"
    :vartype NAME: str
    """

    GID = "gid"
    OSMID = "osm_id"
    FCLASS = "fclass"
    NAME = "name"

    def list():
        """Lists all category values.

        :return: A list of all category values.
        :rtype: list
        """
        return list(
            map(
                lambda x: x.value, GetOgrGpkgPoiFeaturesProperties._member_map_.values()
            )
        )
