# This file was generated by liblab | https://liblab.com/

from enum import Enum


class GetMapF(Enum):
    """An enumeration representing different categories.

    :cvar PNG: "png"
    :vartype PNG: str
    """

    PNG = "png"

    def list():
        """Lists all category values.

        :return: A list of all category values.
        :rtype: list
        """
        return list(map(lambda x: x.value, GetMapF._member_map_.values()))
