# This file was generated by liblab | https://liblab.com/

from enum import Enum


class JobControlOptions(Enum):
    """An enumeration representing different categories.

    :cvar SYNCEXECUTE: "sync-execute"
    :vartype SYNCEXECUTE: str
    :cvar ASYNCEXECUTE: "async-execute"
    :vartype ASYNCEXECUTE: str
    :cvar DISMISS: "dismiss"
    :vartype DISMISS: str
    """

    SYNCEXECUTE = "sync-execute"
    ASYNCEXECUTE = "async-execute"
    DISMISS = "dismiss"

    def list():
        """Lists all category values.

        :return: A list of all category values.
        :rtype: list
        """
        return list(map(lambda x: x.value, JobControlOptions._member_map_.values()))
