# This file was generated by liblab | https://liblab.com/

from __future__ import annotations
from typing import List
from .utils.json_map import JsonMap
from .utils.base_model import BaseModel
from .link import Link


@JsonMap({})
class LandingPage(BaseModel):
    """LandingPage

    :param title: title, defaults to None
    :type title: str, optional
    :param description: description, defaults to None
    :type description: str, optional
    :param links: links
    :type links: List[Link]
    """

    def __init__(self, links: List[Link], title: str = None, description: str = None):
        """LandingPage

        :param title: title, defaults to None
        :type title: str, optional
        :param description: description, defaults to None
        :type description: str, optional
        :param links: links
        :type links: List[Link]
        """
        if title is not None:
            self.title = title
        if description is not None:
            self.description = description
        self.links = self._define_list(links, Link)
