# This file was generated by liblab | https://liblab.com/

from enum import Enum


class Lang(Enum):
    """An enumeration representing different categories.

    :cvar ENUS: "en-US"
    :vartype ENUS: str
    """

    ENUS = "en-US"

    def list():
        """Lists all category values.

        :return: A list of all category values.
        :rtype: list
        """
        return list(map(lambda x: x.value, Lang._member_map_.values()))
