# This file was generated by liblab | https://liblab.com/

from .utils.json_map import JsonMap
from .utils.base_model import BaseModel


@JsonMap({})
class Metadata(BaseModel):
    """Metadata

    :param title: title, defaults to None
    :type title: str, optional
    :param role: role, defaults to None
    :type role: str, optional
    :param href: href, defaults to None
    :type href: str, optional
    """

    def __init__(self, title: str = None, role: str = None, href: str = None):
        """Metadata

        :param title: title, defaults to None
        :type title: str, optional
        :param role: role, defaults to None
        :type role: str, optional
        :param href: href, defaults to None
        :type href: str, optional
        """
        if title is not None:
            self.title = title
        if role is not None:
            self.role = role
        if href is not None:
            self.href = href
