# This file was generated by liblab | https://liblab.com/

from enum import Enum
from typing import List
from .utils.json_map import JsonMap
from .utils.base_model import BaseModel


class PolygonGeoJsonType(Enum):
    """An enumeration representing different categories.

    :cvar POLYGON: "Polygon"
    :vartype POLYGON: str
    """

    POLYGON = "Polygon"

    def list():
        """Lists all category values.

        :return: A list of all category values.
        :rtype: list
        """
        return list(map(lambda x: x.value, PolygonGeoJsonType._member_map_.values()))


@JsonMap({"type_": "type"})
class PolygonGeoJson(BaseModel):
    """PolygonGeoJson

    :param type_: type_
    :type type_: PolygonGeoJsonType
    :param coordinates: coordinates
    :type coordinates: List[List[List[float]]]
    """

    def __init__(self, type_: PolygonGeoJsonType, coordinates: List[List[List[float]]]):
        """PolygonGeoJson

        :param type_: type_
        :type type_: PolygonGeoJsonType
        :param coordinates: coordinates
        :type coordinates: List[List[List[float]]]
        """
        self.type_ = self._enum_matching(type_, PolygonGeoJsonType.list(), "type_")
        self.coordinates = coordinates
