# This file was generated by liblab | https://liblab.com/

from __future__ import annotations
from typing import List
from .utils.json_map import JsonMap
from .utils.base_model import BaseModel
from .process_summary import ProcessSummary
from .link_3 import Link3


@JsonMap({})
class ProcessList(BaseModel):
    """ProcessList

    :param processes: processes
    :type processes: List[ProcessSummary]
    :param links: links
    :type links: List[Link3]
    """

    def __init__(self, processes: List[ProcessSummary], links: List[Link3]):
        """ProcessList

        :param processes: processes
        :type processes: List[ProcessSummary]
        :param links: links
        :type links: List[Link3]
        """
        self.processes = self._define_list(processes, ProcessSummary)
        self.links = self._define_list(links, Link3)
