# This file was generated by liblab | https://liblab.com/

from __future__ import annotations
from typing import List
from .utils.json_map import JsonMap
from .utils.base_model import BaseModel
from .queryable import Queryable


@JsonMap({})
class Queryables(BaseModel):
    """Queryables

    :param queryables: queryables
    :type queryables: List[Queryable]
    """

    def __init__(self, queryables: List[Queryable]):
        """Queryables

        :param queryables: queryables
        :type queryables: List[Queryable]
        """
        self.queryables = self._define_list(queryables, Queryable)
