# This file was generated by liblab | https://liblab.com/

from typing import Union
from typing import List
from .utils.one_of_base_model import OneOfBaseModel


class QueryCubeIcoadsSstBboxGuard(OneOfBaseModel):
    class_list = {"List[float]": List[float], "List[float]": List[float]}


QueryCubeIcoadsSstBbox = Union[List[float], List[float]]
