# This file was generated by liblab | https://liblab.com/

from __future__ import annotations
from typing import List
from .utils.json_map import JsonMap
from .utils.base_model import BaseModel
from .reference_system import ReferenceSystem


@JsonMap({})
class ReferenceSystemConnection(BaseModel):
    """Reference System Connection object: connects coordinates to reference systems

    :param coordinates: coordinates
    :type coordinates: List[str]
    :param system: system
    :type system: ReferenceSystem
    """

    def __init__(self, coordinates: List[str], system: ReferenceSystem):
        """Reference System Connection object: connects coordinates to reference systems

        :param coordinates: coordinates
        :type coordinates: List[str]
        :param system: system
        :type system: ReferenceSystem
        """
        self.coordinates = coordinates
        self.system = self._define_object(system, ReferenceSystem)
