# This file was generated by liblab | https://liblab.com/

from .utils.json_map import JsonMap
from .utils.base_model import BaseModel


@JsonMap({"type_": "type"})
class ReferenceSystem(BaseModel):
    """ReferenceSystem

    :param type_: type_
    :type type_: str
    """

    def __init__(self, type_: str):
        """ReferenceSystem

        :param type_: type_
        :type type_: str
        """
        self.type_ = type_
