# This file was generated by liblab | https://liblab.com/

from enum import Enum


class StatusCode(Enum):
    """An enumeration representing different categories.

    :cvar ACCEPTED: "accepted"
    :vartype ACCEPTED: str
    :cvar RUNNING: "running"
    :vartype RUNNING: str
    :cvar SUCCESSFUL: "successful"
    :vartype SUCCESSFUL: str
    :cvar FAILED: "failed"
    :vartype FAILED: str
    :cvar DISMISSED: "dismissed"
    :vartype DISMISSED: str
    """

    ACCEPTED = "accepted"
    RUNNING = "running"
    SUCCESSFUL = "successful"
    FAILED = "failed"
    DISMISSED = "dismissed"

    def list():
        """Lists all category values.

        :return: A list of all category values.
        :rtype: list
        """
        return list(map(lambda x: x.value, StatusCode._member_map_.values()))
