# This file was generated by liblab | https://liblab.com/

from __future__ import annotations
from typing import List
from .utils.json_map import JsonMap
from .utils.base_model import BaseModel
from .link_2 import Link2
from .tilematrixsetlink import Tilematrixsetlink


@JsonMap({"tile_matrix_set_links": "tileMatrixSetLinks"})
class Tiles(BaseModel):
    """Tiles

    :param links: links
    :type links: List[Link2]
    :param tile_matrix_set_links: tile_matrix_set_links
    :type tile_matrix_set_links: List[Tilematrixsetlink]
    """

    def __init__(
        self, links: List[Link2], tile_matrix_set_links: List[Tilematrixsetlink]
    ):
        """Tiles

        :param links: links
        :type links: List[Link2]
        :param tile_matrix_set_links: tile_matrix_set_links
        :type tile_matrix_set_links: List[Tilematrixsetlink]
        """
        self.links = self._define_list(links, Link2)
        self.tile_matrix_set_links = self._define_list(
            tile_matrix_set_links, Tilematrixsetlink
        )
