# This file was generated by liblab | https://liblab.com/

from enum import Enum


class TileMatrixSets(Enum):
    """An enumeration representing different categories.

    :cvar WEBMERCATORQUAD: "WebMercatorQuad"
    :vartype WEBMERCATORQUAD: str
    :cvar WORLDCRS84QUAD: "WorldCRS84Quad"
    :vartype WORLDCRS84QUAD: str
    :cvar GNOSISGLOBALGRID: "GNOSISGlobalGrid"
    :vartype GNOSISGLOBALGRID: str
    :cvar WORLDMERCATORWGS84QUAD: "WorldMercatorWGS84Quad"
    :vartype WORLDMERCATORWGS84QUAD: str
    """

    WEBMERCATORQUAD = "WebMercatorQuad"
    WORLDCRS84QUAD = "WorldCRS84Quad"
    GNOSISGLOBALGRID = "GNOSISGlobalGrid"
    WORLDMERCATORWGS84QUAD = "WorldMercatorWGS84Quad"

    def list():
        """Lists all category values.

        :return: A list of all category values.
        :rtype: list
        """
        return list(map(lambda x: x.value, TileMatrixSets._member_map_.values()))
