# This file was generated by liblab | https://liblab.com/

from enum import Enum


class TransmissionMode(Enum):
    """An enumeration representing different categories.

    :cvar VALUE: "value"
    :vartype VALUE: str
    :cvar REFERENCE: "reference"
    :vartype REFERENCE: str
    """

    VALUE = "value"
    REFERENCE = "reference"

    def list():
        """Lists all category values.

        :return: A list of all category values.
        :rtype: list
        """
        return list(map(lambda x: x.value, TransmissionMode._member_map_.values()))
