# This file was generated by liblab | https://liblab.com/

from geobeyond_sdk import GeobeyondSdk, Environment
from geobeyond_sdk.models import GetLandingPageF, Lang

sdk = GeobeyondSdk(base_url=Environment.DEFAULT.value, timeout=10000)

result = sdk.server.get_landing_page(f="json", lang="en-US")

print(result)
